### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by alwans** [77Z/electron-injector#1]
I ran this application, but did not find the open button.

//Welcome to Electron Injector!
//To start injecting, press the open button
// <= Over Here!

**Comment by 77Z** [comment]
This Project isn't finished yet, sorry

**Comment by alwans** [comment]
If you have rich experience in electron decompilation, can you help me crack an electron application for a fee?

**Comment by 77Z** [comment]
Yeah sure, preferably some time on the weekend.

**Comment by alwans** [comment]
Give me an email address where I can contact you

**Comment by 77Z** [comment]
r2d2fan20@outlook.com
